default: &default
  toolbar:
    - styleselect | bold italic | undo redo
    - image | link
  plugins:
    - image
    - link

alternate:
  <<: *default
  menubar: false
  toolbar: bold italic forecolor| undo redo | table
  plugins:
    - table
